repos:
  - repo: local
    hooks:
      - id: gen-proto
        name: Generate event protobuf
        entry: python scripts/gen_proto.py
        language: system
        files: ^proto/event\.proto$
        pass_filenames: false
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        args: ["--line-length=100"]
