repos:
  - repo: local
    hooks:
      - id: gen-proto
        name: Generate event protobuf
        entry: python scripts/gen_proto.py
        language: system
        files: ^proto/event\.proto$
        pass_filenames: false
