"""Structured event models for the Golden Snapshot pipeline."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Sequence


Timestamp = float

OHLCV_BAR_SCHEMA_VERSION = "2.0"
GOLDEN_SNAPSHOT_SCHEMA_VERSION = "2.0"
TOKEN_SNAPSHOT_SCHEMA_VERSION = "1.0"
DEPTH_SNAPSHOT_SCHEMA_VERSION = "1.0"
TRADE_SUGGESTION_SCHEMA_VERSION = "1.0"
DECISION_SCHEMA_VERSION = "1.0"
VIRTUAL_FILL_SCHEMA_VERSION = "1.0"
LIVE_FILL_SCHEMA_VERSION = "1.0"
TRADE_REJECTION_SCHEMA_VERSION = "1.0"


@dataclass(slots=True)
class DiscoveryCandidate:
    """Token identified by the discovery stage."""

    mint: str
    asof: Timestamp
    source: str | None = None
    sources: tuple[str, ...] = field(default_factory=tuple)
    v: str = "1.0"


@dataclass(slots=True)
class TokenSnapshot:
    """Token metadata emitted by the enrichment stage."""

    mint: str
    symbol: str
    name: str
    decimals: int
    token_program: str
    venues: Sequence[str] | None = None
    flags: Dict[str, Any] = field(default_factory=dict)
    asof: Timestamp = 0.0
    schema_version: str = field(default=TOKEN_SNAPSHOT_SCHEMA_VERSION)


@dataclass(slots=True)
class TapeEvent:
    """Normalised swap or trade event from on-chain market data."""

    mint_base: str
    mint_quote: str
    amount_base: float
    amount_quote: float
    route: str
    program_id: str
    pool: str
    signer: str
    signature: str
    slot: int
    ts: Timestamp
    fees_base: float
    price_usd: float
    fees_usd: float
    is_self: bool = False
    buyer: Optional[str] = None


@dataclass(slots=True)
class OHLCVBar:
    """Closed 5-minute OHLCV bar."""

    mint: str
    open: float
    high: float
    low: float
    close: float
    vol_usd: float
    vol_base: float
    trades: int
    buyers: int
    flow_usd: float
    zret: float
    zvol: float
    asof_close: Timestamp
    schema_version: str = field(default=OHLCV_BAR_SCHEMA_VERSION)


@dataclass(slots=True)
class DepthSnapshot:
    """Executable depth snapshot for a token."""

    mint: str
    venue: str
    mid_usd: float
    spread_bps: float
    depth_pct: Dict[str, float]
    asof: Timestamp
    px_bid_usd: float | None = None
    px_ask_usd: float | None = None
    depth_bands_usd: Dict[str, float] | None = None
    degraded: bool = False
    source: str | None = None
    route_meta: Dict[str, Any] | None = None
    staleness_ms: float | None = None
    schema_version: str = field(default=DEPTH_SNAPSHOT_SCHEMA_VERSION)


@dataclass(slots=True)
class GoldenSnapshot:
    """Canonical input consumed by agents."""

    mint: str
    asof: Timestamp
    meta: Dict[str, Any]
    px: Dict[str, Any]
    liq: Dict[str, Any]
    ohlcv5m: Dict[str, Any]
    hash: str
    content_hash: str = ""
    idempotency_key: str = ""
    metrics: Dict[str, Any] = field(default_factory=dict)
    momentum_score: float | None = None
    pump_intensity: float | None = None
    pump_score: float | None = None
    social_score: float | None = None
    social_sentiment: float | None = None
    tweets_per_min: float | None = None
    momentum_sources: tuple[str, ...] = field(default_factory=tuple)
    momentum_breakdown: Dict[str, Any] = field(default_factory=dict)
    momentum_partial: bool = False
    momentum_stale: bool = False
    schema_version: str = field(default=GOLDEN_SNAPSHOT_SCHEMA_VERSION)


@dataclass(slots=True)
class TradeSuggestion:
    """Deterministic agent output derived from a Golden Snapshot."""

    agent: str
    mint: str
    side: str
    notional_usd: float
    max_slippage_bps: float
    risk: Dict[str, Any]
    confidence: float
    inputs_hash: str
    ttl_sec: float
    generated_at: Timestamp
    gating: Dict[str, Any] = field(default_factory=dict)
    slices: List[Dict[str, Any]] = field(default_factory=list)
    must_exit: bool = False
    hot_watch: bool = False
    exit_diagnostics: Dict[str, Any] = field(default_factory=dict)
    sequence: int = 0
    schema_version: str = field(default=TRADE_SUGGESTION_SCHEMA_VERSION)


@dataclass(slots=True)
class Decision:
    """Swarm-voted trading decision."""

    mint: str
    side: str
    notional_usd: float
    score: float
    snapshot_hash: str
    client_order_id: str
    agents: List[str]
    ts: Timestamp
    sequence: int = 0
    schema_version: str = field(default=DECISION_SCHEMA_VERSION)


@dataclass(slots=True)
class VirtualFill:
    """Synthetic fill generated by the shadow executor."""

    order_id: str
    mint: str
    side: str
    qty_base: float
    price_usd: float
    fees_usd: float
    slippage_bps: float
    snapshot_hash: str
    route: str
    ts: Timestamp
    schema_version: str = field(default=VIRTUAL_FILL_SCHEMA_VERSION)


@dataclass(slots=True)
class LiveFill:
    """Real fill generated by the live executor."""

    sig: str
    mint: str
    side: str
    qty_base: float
    price_usd: float
    fees_usd: float
    slippage_bps: float
    route: str
    snapshot_hash: str
    schema_version: str = field(default=LIVE_FILL_SCHEMA_VERSION)


@dataclass(slots=True)
class VirtualPnL:
    """Paper trading PnL derived from virtual fills."""

    order_id: str
    mint: str
    snapshot_hash: str
    realized_usd: float
    unrealized_usd: float
    ts: Timestamp

