name: Data freshness

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  price-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Ensure price data is recent
        env:
          PRICES_MAX_AGE_MONTHS: 6
        run: |
          python scripts/check_prices_data_freshness.py

  schema-fastpath:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install project (dev)
        run: |
          python -m pip install -U pip
          pip install -e ".[dev]"
      - name: Lint & compile
        run: |
          ruff check .
          python -m compileall -q solhunter_zero
      - name: Test (schema E2E fast path)
        run: |
          pytest tests/golden_pipeline/test_end_to_end_schema.py --maxfail=1 --disable-warnings -q
