"""JSON Schema definitions for Golden pipeline bus streams."""

from __future__ import annotations

from typing import Any, Dict, Mapping

from ..golden_pipeline.contracts import STREAMS
from ..golden_pipeline.types import (
    DECISION_SCHEMA_VERSION,
    DEPTH_SNAPSHOT_SCHEMA_VERSION,
    GOLDEN_SNAPSHOT_SCHEMA_VERSION,
    LIVE_FILL_SCHEMA_VERSION,
    TOKEN_SNAPSHOT_SCHEMA_VERSION,
    TRADE_REJECTION_SCHEMA_VERSION,
    TRADE_SUGGESTION_SCHEMA_VERSION,
    VIRTUAL_FILL_SCHEMA_VERSION,
)


def _number() -> Dict[str, Any]:
    return {"type": "number"}


STREAM_SCHEMAS: Mapping[str, Dict[str, Any]] = {
    STREAMS.discovery_candidates: {
        "type": "object",
        "properties": {
            "mint": {"type": "string", "minLength": 1},
            "asof": _number(),
        },
        "required": ["mint", "asof"],
        "additionalProperties": True,
    },
    STREAMS.token_snapshot: {
        "type": "object",
        "properties": {
            "mint": {"type": "string", "minLength": 1},
            "symbol": {"type": "string"},
            "name": {"type": "string"},
            "decimals": {"type": "integer", "minimum": 0},
            "token_program": {"type": "string", "minLength": 1},
            "venues": {"type": ["array", "null"], "items": {"type": "string"}},
            "flags": {"type": "object"},
            "asof": _number(),
            "schema_version": {"const": TOKEN_SNAPSHOT_SCHEMA_VERSION},
        },
        "required": [
            "mint",
            "symbol",
            "name",
            "decimals",
            "token_program",
            "asof",
            "schema_version",
        ],
        "additionalProperties": True,
    },
    STREAMS.market_ohlcv: {
        "type": "object",
        "properties": {
            "mint": {"type": "string", "minLength": 1},
            "o": _number(),
            "h": _number(),
            "l": _number(),
            "c": _number(),
            "vol_usd": _number(),
            "trades": {"type": "integer", "minimum": 0},
            "buyers": {"type": "integer", "minimum": 0},
            "zret": _number(),
            "zvol": _number(),
            "asof_close": _number(),
        },
        "required": [
            "mint",
            "o",
            "h",
            "l",
            "c",
            "vol_usd",
            "trades",
            "buyers",
            "zret",
            "zvol",
            "asof_close",
        ],
        "additionalProperties": True,
    },
    STREAMS.market_depth: {
        "type": "object",
        "properties": {
            "mint": {"type": "string", "minLength": 1},
            "venue": {"type": "string", "minLength": 1},
            "mid_usd": _number(),
            "spread_bps": _number(),
            "depth_pct": {
                "type": "object",
                "additionalProperties": _number(),
            },
            "asof": _number(),
            "schema_version": {"const": DEPTH_SNAPSHOT_SCHEMA_VERSION},
        },
        "required": ["mint", "venue", "mid_usd", "spread_bps", "depth_pct", "asof", "schema_version"],
        "additionalProperties": True,
    },
    STREAMS.golden_snapshot: {
        "type": "object",
        "properties": {
            "mint": {"type": "string", "minLength": 1},
            "asof": _number(),
            "meta": {"type": "object"},
            "px": {"type": "object"},
            "liq": {"type": "object"},
            "ohlcv5m": {"type": "object"},
            "hash": {"type": "string", "minLength": 1},
            "metrics": {"type": "object"},
            "schema_version": {"const": GOLDEN_SNAPSHOT_SCHEMA_VERSION},
        },
        "required": [
            "mint",
            "asof",
            "meta",
            "px",
            "liq",
            "ohlcv5m",
            "hash",
            "schema_version",
        ],
        "additionalProperties": True,
    },
    STREAMS.trade_suggested: {
        "type": "object",
        "properties": {
            "agent": {"type": "string", "minLength": 1},
            "mint": {"type": "string", "minLength": 1},
            "side": {"type": "string", "minLength": 3},
            "notional_usd": _number(),
            "max_slippage_bps": _number(),
            "risk": {"type": "object"},
            "confidence": _number(),
            "inputs_hash": {"type": "string", "minLength": 1},
            "ttl_sec": _number(),
            "generated_at": _number(),
            "gating": {"type": "object"},
            "slices": {"type": "array", "items": {"type": "object"}},
            "must_exit": {"type": "boolean"},
            "hot_watch": {"type": "boolean"},
            "exit_diagnostics": {"type": "object"},
            "sequence": {"type": "integer", "minimum": 0},
            "schema_version": {"const": TRADE_SUGGESTION_SCHEMA_VERSION},
        },
        "required": [
            "agent",
            "mint",
            "side",
            "notional_usd",
            "max_slippage_bps",
            "risk",
            "confidence",
            "inputs_hash",
            "ttl_sec",
            "generated_at",
            "sequence",
            "schema_version",
        ],
        "additionalProperties": True,
    },
    STREAMS.trade_rejected: {
        "type": "object",
        "properties": {
            "agent": {"type": "string", "minLength": 1},
            "source_agent": {"type": "string", "minLength": 1},
            "mint": {"type": "string", "minLength": 1},
            "side": {"type": "string", "minLength": 3},
            "notional_usd": _number(),
            "max_slippage_bps": _number(),
            "confidence": _number(),
            "ttl_sec": _number(),
            "snapshot_hash": {"type": "string", "minLength": 1},
            "asof": _number(),
            "detected_at": _number(),
            "gating": {"type": "object"},
            "reason": {"type": ["string", "null"]},
            "reason_code": {"type": ["string", "null"]},
            "guard": {"type": ["string", "null"]},
            "scope": {"type": ["string", "null"]},
            "schema_version": {"const": TRADE_REJECTION_SCHEMA_VERSION},
        },
        "required": [
            "agent",
            "source_agent",
            "mint",
            "side",
            "notional_usd",
            "max_slippage_bps",
            "confidence",
            "ttl_sec",
            "snapshot_hash",
            "asof",
            "detected_at",
            "gating",
            "schema_version",
        ],
        "additionalProperties": True,
    },
    STREAMS.vote_decisions: {
        "type": "object",
        "properties": {
            "mint": {"type": "string", "minLength": 1},
            "side": {"type": "string", "minLength": 3},
            "notional_usd": _number(),
            "score": _number(),
            "snapshot_hash": {"type": "string", "minLength": 1},
            "client_order_id": {"type": "string", "minLength": 1},
            "agents": {"type": "array", "items": {"type": "string"}},
            "ts": _number(),
            "sequence": {"type": "integer", "minimum": 0},
            "schema_version": {"const": DECISION_SCHEMA_VERSION},
        },
        "required": [
            "mint",
            "side",
            "notional_usd",
            "score",
            "snapshot_hash",
            "client_order_id",
            "agents",
            "ts",
            "sequence",
            "schema_version",
        ],
        "additionalProperties": True,
    },
    STREAMS.virtual_fills: {
        "type": "object",
        "properties": {
            "order_id": {"type": "string", "minLength": 1},
            "mint": {"type": "string", "minLength": 1},
            "side": {"type": "string", "minLength": 3},
            "qty_base": _number(),
            "price_usd": _number(),
            "fees_usd": _number(),
            "slippage_bps": _number(),
            "snapshot_hash": {"type": "string", "minLength": 1},
            "route": {"type": "string", "minLength": 1},
            "ts": _number(),
            "schema_version": {"const": VIRTUAL_FILL_SCHEMA_VERSION},
        },
        "required": [
            "order_id",
            "mint",
            "side",
            "qty_base",
            "price_usd",
            "fees_usd",
            "slippage_bps",
            "snapshot_hash",
            "route",
            "ts",
            "schema_version",
        ],
        "additionalProperties": True,
    },
    STREAMS.live_fills: {
        "type": "object",
        "properties": {
            "sig": {"type": "string", "minLength": 1},
            "mint": {"type": "string", "minLength": 1},
            "side": {"type": "string", "minLength": 3},
            "qty_base": _number(),
            "price_usd": _number(),
            "fees_usd": _number(),
            "slippage_bps": _number(),
            "route": {"type": "string", "minLength": 1},
            "snapshot_hash": {"type": "string", "minLength": 1},
            "schema_version": {"const": LIVE_FILL_SCHEMA_VERSION},
        },
        "required": [
            "sig",
            "mint",
            "side",
            "qty_base",
            "price_usd",
            "fees_usd",
            "slippage_bps",
            "route",
            "snapshot_hash",
            "schema_version",
        ],
        "additionalProperties": True,
    },
}

__all__ = ["STREAM_SCHEMAS"]
